-- ============================================================
-- 017 (2026-08-26): 주말 모의고사 출제·OMR — 수파베이스가 원본이 된다
--
-- 지금까지 omr_exams(회차정답)·omr_responses(응답)는 OMR 시트의 읽기 미러였다(005).
-- 이제 출제 저장·학생 제출·성적 조회가 여기에서 이뤄지고, 시트는 페이지가 뒤에서
-- 이중 기록하는 사본이 된다(신청 signup_entries 016 전환과 같은 방향).
--
-- OMR 학생·교사 화면은 Apps Script 안(iframe·google.script.run)에 있어 미러가 불가능했는데,
-- 이번에 정적 페이지(shueguk-hub omr.html·omr_teacher.html)로 옮기면서 가능해졌다.
--
-- 채점(scoreAndBuild)은 **여기 DB 함수로 옮겼다**(omr_score_build_) — 정답·배점이 담긴 회차
-- 데이터(omr_exams)는 anon이 읽을 수 없으므로, 학생은 제출(omr_submit)·본인 성적 조회
-- (omr_student_reports)를 통해서만 채점 결과(정오표 포함)를 받는다. 옛 백엔드와 같은 공개 수준
-- (제출 후에만 정답 노출, 본인 것만 조회).
--
-- 회차 데이터 모양 (omr_code.gs·answer_key.html 그대로):
--   고3형: {화법과작문:{code,date,grade,subject,cuts,answers,points,areas}, 언어와매체:{...}}
--   통합형: {mode:'통합', 통합:{...}} — 선택과목 없이 '공통'으로 채점
--   answers/points: {'1':5,...'45':3}, areas: [{cat,name,qs:[1,2,3]},...], cuts: [87,79,70,63]
-- ============================================================

-- 회차 목록 순서 — 시트는 행 순서(추가된 순서)였다. seq로 재현(새 회차는 자동 증가).
alter table omr_exams add column if not exists seq bigint generated by default as identity;

-- ── 채점 (scoreAndBuild 1:1 이식) — 내부용: 회차 데이터를 인자로 받으므로
--    이 함수 자체는 정답을 새로 노출하지 않는다(데이터를 가진 쪽만 쓸 수 있음)
create or replace function public.omr_score_build_(p_pack jsonb, p jsonb)
returns jsonb
language plpgsql immutable
as $$
declare
  v_subject text := coalesce(p->>'subject', '');
  exam jsonb;
  detail jsonb := '{}'::jsonb;
  areas jsonb := '[]'::jsonb;
  a jsonb; q int; qs text;
  v_ans text; v_mine text; v_ok boolean; v_pt numeric;
  total numeric := 0; got numeric := 0;
  f numeric; s numeric;
  cuts jsonb; v_grade text := '등급외';
begin
  if p_pack ? '통합' then
    exam := p_pack->'통합';
    v_subject := '공통';
  else
    if v_subject <> '화법과작문' then v_subject := '언어와매체'; end if;
    exam := p_pack->v_subject;
    if exam is null then
      return jsonb_build_object('ok', false, 'error', '선택과목 정답이 없습니다: ' || v_subject);
    end if;
  end if;

  for q in 1..45 loop
    qs := q::text;
    v_ans := exam->'answers'->>qs;
    v_mine := coalesce(p->'answers'->>qs, '');
    v_ok := v_ans is not null and v_mine <> '' and v_mine = v_ans;
    v_pt := coalesce((exam->'points'->>qs)::numeric, 0);
    detail := detail || jsonb_build_object(qs, jsonb_build_object(
      'ans', coalesce(v_ans, ''), 'mine', v_mine, 'pt', v_pt, 'ok', v_ok));
    total := total + v_pt;
    if v_ok then got := got + v_pt; end if;
  end loop;

  for a in select * from jsonb_array_elements(exam->'areas') loop
    f := 0; s := 0;
    for qs in select value::text from jsonb_array_elements(a->'qs') loop
      v_pt := coalesce((exam->'points'->>qs)::numeric, 0);
      f := f + v_pt;
      if (detail->qs->>'ok')::boolean then s := s + v_pt; end if;
    end loop;
    areas := areas || jsonb_build_object(
      'cat', a->>'cat', 'name', a->>'name', 'full', f, 'score', s,
      'rate', case when f > 0 then round(s / f * 100) else 0 end);
  end loop;

  cuts := exam->'cuts';
  if    got >= (cuts->>0)::numeric then v_grade := '1';
  elsif got >= (cuts->>1)::numeric then v_grade := '2';
  elsif got >= (cuts->>2)::numeric then v_grade := '3';
  elsif got >= (cuts->>3)::numeric then v_grade := '4';
  end if;

  return jsonb_build_object(
    'ok', true,
    'student', jsonb_build_object('name', p->>'name', 'school', p->>'school',
      'grade', p->>'grade', 'subject', v_subject, 'examDate', p->>'examDate'),
    'exam', jsonb_build_object('code', exam->>'code', 'date', exam->>'date',
      'subject', exam->>'subject', 'cuts', cuts),
    'result', jsonb_build_object('total', total, 'got', got, 'grade', v_grade,
      'areas', areas, 'detail', detail));
end $$;

-- ── 회차 목록 (getExamList2 와 같은 모양 — 이름·형식만, 정답은 안 나감) ──
create or replace function public.omr_exam_list()
returns jsonb
language sql stable security definer set search_path = public
as $$
  select coalesce(jsonb_agg(jsonb_build_object('name', name, 'mode', mode) order by seq), '[]'::jsonb)
  from omr_exams
$$;

-- ── 학생 제출 → 채점 → 기록 → 성적표 반환 (submitOMR 와 같은 흐름·응답 모양) ──
-- p = {examName, examDate, name, school, grade, subject, answers{'1'..'45'}, studentId}
create or replace function public.omr_submit(p jsonb)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_exam text := trim(coalesce(p->>'examName', ''));
  v_pack jsonb;
  rep jsonb;
begin
  select data::jsonb into v_pack from omr_exams where name = v_exam;
  if v_pack is null then
    return jsonb_build_object('ok', false, 'error', '회차를 찾을 수 없습니다: ' || v_exam);
  end if;
  rep := omr_score_build_(v_pack, p);
  if not (rep->>'ok')::boolean then return rep; end if;
  insert into omr_responses (exam, exam_date, name, school, grade, subject,
                             got, total, level, answers, student_id)
  values (v_exam, coalesce(p->>'examDate', ''), trim(coalesce(p->>'name', '')),
          trim(coalesce(p->>'school', '')), coalesce(p->>'grade', ''),
          rep->'student'->>'subject',
          rep->'result'->>'got', rep->'result'->>'total', rep->'result'->>'grade',
          coalesce(p->'answers', '{}'::jsonb), coalesce(p->>'studentId', ''));
  return rep;
end $$;

-- ── 학생 개별 페이지: 본인 성적표 목록 (studentReports_ 와 같은 매칭·모양) ──
-- p = {name, school, id, uniq} — 이름+학교(느슨) 1차, 학생ID는 동명이인 보조, uniq=1이면 생략
create or replace function public.omr_student_reports(p jsonb)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare
  v_name   text := trim(coalesce(p->>'name', ''));
  v_school text := trim(coalesce(p->>'school', ''));
  v_id     text := trim(coalesce(p->>'id', ''));
  v_uniq   boolean := coalesce(p->>'uniq', '') = '1';
  r record;
  packs jsonb := '{}'::jsonb;   -- 회차 데이터 캐시 (회차마다 한 번만 파싱)
  pack jsonb; rep jsonb;
  v_out jsonb := '[]'::jsonb;
begin
  if v_name = '' then
    return jsonb_build_object('result', 'success', 'reports', '[]'::jsonb);
  end if;
  for r in
    select * from omr_responses
    where trim(name) = v_name
      and (v_school = '' or trim(school) = '' or signup_school_match(school, v_school))
      and (v_uniq or trim(student_id) = '' or v_id = '' or trim(student_id) = v_id)
    order by submitted_at desc, id desc
  loop
    if packs ? r.exam then
      pack := packs->r.exam;
    else
      select data::jsonb into pack from omr_exams where name = r.exam;
      if pack is null then continue; end if;   -- 정답 없는 옛 회차는 건너뜀 (백엔드와 동일)
      packs := packs || jsonb_build_object(r.exam, pack);
    end if;
    rep := omr_score_build_(pack, jsonb_build_object(
      'examName', r.exam, 'examDate', r.exam_date, 'name', r.name, 'school', r.school,
      'grade', r.grade, 'subject', r.subject, 'answers', r.answers));
    if not (rep->>'ok')::boolean then continue; end if;
    v_out := v_out || jsonb_build_object(
      'examName', r.exam, 'examDate', r.exam_date,
      'subject', rep->'student'->>'subject', 'school', r.school, 'grade', r.grade,
      'got', rep->'result'->'got', 'level', rep->'result'->>'grade',
      'cuts', rep->'exam'->'cuts', 'areas', rep->'result'->'areas',
      'total', rep->'result'->'total', 'detail', rep->'result'->'detail',
      'submittedAt', to_char(r.submitted_at at time zone 'Asia/Seoul', 'YYYY-MM-DD HH24:MI:SS'));
  end loop;
  return jsonb_build_object('result', 'success', 'reports', v_out);
end $$;

-- ── 교사 성적 관리: 저장된 한 건의 성적표 다시 만들기 (getReportByRow 대체, id 기준) ──
create or replace function public.omr_report_by_id(p jsonb)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare
  r omr_responses%rowtype;
  pack jsonb;
begin
  select * into r from omr_responses where id = (p->>'id')::bigint;
  if r.id is null then
    return jsonb_build_object('ok', false, 'error', '해당 기록을 찾을 수 없습니다');
  end if;
  select data::jsonb into pack from omr_exams where name = r.exam;
  if pack is null then
    return jsonb_build_object('ok', false, 'error', '회차를 찾을 수 없습니다: ' || r.exam);
  end if;
  return omr_score_build_(pack, jsonb_build_object(
    'examName', r.exam, 'examDate', r.exam_date, 'name', r.name, 'school', r.school,
    'grade', r.grade, 'subject', r.subject, 'answers', r.answers));
end $$;

-- 학생 화면(공개 키): 회차 목록·제출·본인 성적만. 성적 관리용 재채점은 교사 신분만.
grant execute on function public.omr_exam_list()             to anon, authenticated;
grant execute on function public.omr_submit(jsonb)           to anon, authenticated;
grant execute on function public.omr_student_reports(jsonb)  to anon, authenticated;
revoke execute on function public.omr_report_by_id(jsonb) from public, anon;
grant execute on function public.omr_report_by_id(jsonb)     to authenticated;
